#!/usr/local/cs/bin/bash

export LC_ALL='\en_US.UTF-8'

dir=$1
RESULT=`ls -a $dir`
declare -a ARRAY
let count=0

for FILE in $RESULT
do
  if [ ! -r "$dir/$FILE" ]
  then
      echo "$dir/$FILE is unreadable"
  elif [ -f "$dir/$FILE" ]
  then
      ARRAY[$count]="$dir/$FILE"
      echo "${ARRAY[$count]}is a regular file"
      let count=count+1
  else
      echo "$dir/$FILE is not regular file"
  fi
done

for i in "${ARRAY[@]}"
do
for j in "${ARRAY[@]}"
do
if [ "$i" != "$j" ]
then
cmp -s "$i" "$j"
if [ $? -eq 0 ]
then
ln -f "$i" "$j"
fi
fi
done
done